DROP TABLE IF EXISTS order_items CASCADE;

CREATE TABLE order_items(
id SERIAL PRIMARY KEY NOT NULL,
menu_item_id INTEGER REFERENCES menu_item(id) ON DELETE CASCADE,
order_id INTEGER REFERENCES order(id) ON DELETE CASCADE,
quantity INTEGER  NOT NULL DEFAULT 0
);
