DROP TABLE IF EXISTS menu_item CASCADE;

CREATE TABLE menu_item (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0,
  category_id INTEGER REFERENCES category(id) ON DELETE CASCADE
  );
